### ISSUE TITLE
Connection closed errors

### ISSUE THREAD

**Issue by mkrogemann** [locolupo/couchdb_connector#16]
Happens rarely on local developer workstation. Quite often on Travis CI VMs.

  1) test destroy/3: attempting to delete a document with wrong revision triggers an error (Couchdb.Connector.WriterTest)
     test/couchdb_connector/writer_test.exs:94
     ** (HTTPoison.Error) :closed
     stacktrace:
       (httpoison) lib/httpoison.ex:66: HTTPoison.request!/5
       (couchdb_connector) lib/couchdb_connector/writer.ex:99: Couchdb.Connector.Writer.do_create/2
       test/couchdb_connector/writer_test.exs:95

**Comment by mkrogemann** [comment]
Will not attempt to fix this in production code -- preferring the 'let it crash' solution here. Library clients / applications will have to decide what to do in face of this error.
Will however try to work around the issue in tests to make development and testing process more enjoyable.

**Comment by mkrogemann** [comment]
Now wrapping a retry_on_error function around almost all Couchdb HTTP calls that happen in tests. Looks good, ok to close this now, even if the problem might pop up again in rare cases / calls.
